### ISSUE TITLE
Respect `target` when set in docker-compose

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/build-deploy-tool#108]
In multi-stage builds, docker-compose can optionally build multiple targets from a single dockerfile - this also neatly avoids the docker-compose v2 issue with BuildKit racing dependencies.

We should check for the presence of a `target` in the docker-compose file and if set, pass it through to the [exec-build script](https://github.com/uselagoon/build-deploy-tool/blob/main/legacy/scripts/exec-build.sh#L5)

ref: https://docs.docker.com/engine/reference/commandline/build/#specifying-target-build-stage---target

sample dockerfile:
```
ARG PHP_VERSION=8.1
ARG WEBROOT=public

#
# CLI image
#
FROM uselagoon/php-${PHP_VERSION}-cli-drupal:latest as cli

ARG WEBROOT

COPY composer.json composer.lock /app/
COPY patches /app/patches

RUN composer --ansi install --no-dev --optimize-autoloader --prefer-dist

COPY . /app
RUN mkdir -p -v -m775 /app/public/sites/default/files

# Define where the Drupal Root is located
ENV WEBROOT=${WEBROOT}

#
# Nginx image
#
FROM uselagoon/nginx-drupal:latest as nginx

ARG WEBROOT

COPY --from=cli /app /app

COPY lagoon/redirects-map.conf /etc/nginx/redirects-map.conf

# Define where the Drupal Root is located
ENV WEBROOT=${WEBROOT}

#
# PHP-FPM image
#
FROM uselagoon/php-${PHP_VERSION}-fpm:latest as php

RUN docker-php-ext-install exif && docker-php-ext-enable exif

COPY --from=cli /app /app
```
sample docker-compose snippet:
```
  cli:
    build:
      context: .
      target: cli
    ...
  nginx:
    build:
      context .
      target: nginx
  php:
    build:
      context: .
      target: php
      ```
