### ISSUE TITLE
Support for wildcard routes

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/build-deploy-tool#202]
At present Lagoon expects each and every domain to be enumerated in the `.lagoon.yml` file. This poses a challenge for some sites that wish to do application based multi-tenancy, and wish to have all subdomains of a particular root domain forwarded to an application.

## .lagoon.yml changes

```
environments:
  main:
    routes:
      - nginx:
        - "example.com":
            tls-acme: false
        - "www.example.com":
            tls-acme: false
        - "banana.example.com":
            tls-acme: false
```

Rather than having to list every subdomain, add a new `wildcard` flag:

```
environments:
  main:
    routes:
      - nginx:
        - "example.com":
            tls-acme: false
            wildcard: true
```

This will have the effect of routing `example.com` and `*.example.com` to the application within the cluster.

## Known caveats

Lets Encrypt will need to be disabled for all wildcard routes, and TLS will need to be sorted outside Lagoon (e.g. by purchasing a wildcard TLS cert).

## Key goals

- [ ] Support the generation of wildcard ingress objects
- [ ] Update the docs to inform users about wildcard routes
- [ ] Update the Lagoon linter to ensure this is valid YAML
- [ ] Add warning in the build about users attempting to use wildcard routes with `tls-acme` set to `true`. Lagoon should force set this to be `false` and ignore what the user supplies.
