### ISSUE TITLE
Be able to disable autogenerated routes per environment

### ISSUE THREAD

**Issue by dale-c-anderson** [uselagoon/build-deploy-tool#214]
Right now, auto generated routes appear to be an all-or-nothing switch that affect all the environments listed in `.lagoon.yml`.

For staging + production environments, we only want one possible route into the environment, and for it not to be the autogenerated route.  For PR environments, we obviously still want the autogenerated routes. 

This would ensure clients or staff can't use the wrong urls for testing (eg bypassing the CDN/WAF in front of the environment), and if desired, we can enforce security on the environments (that have manually specified routes) by only allowing connections from the CDN/WAF system and nowhere else.

Example:
```
environments:
  production:
    autogenerate:
      enabled: false
    routes:
      - nginx:
          - www.example.com
```

**Comment by shreddedbacon** [comment]
Yep, sorry for the run around. This function already exists.

Usage is as follows
```
environments:
  production:
    autogenerateRoutes: false
    routes:
      - nginx:
          - www.example.com
```
